Resources:
  SampleTopicccCCCcdsadscdasdascsss:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SampleTopicccCCCcdsadscdasdascsss
      Subscription:
        - Endpoint: Your lambda Arn
          Protocol: lambda
        - Endpoint: Your email address
          Protocol: email
