Resources:
  DefaultLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: edgelambda.amazonaws.com
        Version: 2012-10-17
  DefaultLambdaRoleDefaultPolicyD24B795B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: !Join
              - ':'
              - - arn:aws:logs
                - !Ref AWS::Region
                - !Ref AWS::AccountId
                - log-group:/aws/lambda/*:*:*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: !Join
              - ':'
              - - arn:aws:logs:ap-northeast-1
                - !Ref AWS::AccountId
                - log-group:/aws/lambda/*:*:*
        Version: 2012-10-17
      PolicyName: DefaultLambdaRoleDefaultPolicyD24B795B
      Roles:
        - !Ref DefaultLambdaRole
