service: basic-lambda-auth
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: us-east-1
  iam:
    role: DefaultLambdaRole
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    AWS_RESOURCE_PRIFIX: ${self:custom.awsResourcePrefix}
    LOG_LEVEL: WARN
plugins:
  - serverless-webpack
  - serverless-prune-plugin
functions: ${file(./serverless/us-east-1/resources/functions.yml)}
resources:
  - ${file(./serverless/us-east-1/resources/iam-role.yml)}
package:
  individually: true
  includeModules: true
  patterns:
    - '!appsync/*,*'
    - '!node_modules/**'
    - '!resources/**'
    - '!__tests__/**'
    - '!.git/**'
    - '!tmp/**'
custom:
  awsResourcePrefix: ${self:service}-${self:provider.region}-${self:provider.stage}-
  webpack:
    includeModules: true
    packager: npm
  prune:
    automatic: true
    number: 3
